language: node_js
node_js:
  - 7
  - 6
  - 4
before_install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install: yarn install
script: yarn run travis
cache:
  directories:
  - $HOME/.yarn-cache
